
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider"
import SwitchMode from "./SwitchMode"
import Navigate from "../components/Navigate"
import Footer from "../components/Footer.tsx"
import Available from "../components/Available"
import 'react-image-crop/dist/ReactCrop.css'
import Ts from "./Ts"
import Providers from "../components/reduxComponent/provider"
import CheckAuth from "../components/checkData/checkAuth"

import MessageH from "../components/MessageH"
import CookiesSpace from "../components/cookies/CookiesSpace"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "KACSI TECH",
    template: "%s | KACSI TECH",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
           <Providers>
      <Provider>
       <Navigate />
       <CheckAuth/>
       <div>
       <div className="xl:hidden lg:hidden">
       
           {children}

       </div>

       <Ts />
       <div className="hidden xl:block lg:block">
       <Available/>
       </div>
       </div>

        <Footer />
        <MessageH />
        <CookiesSpace />
      </Provider>
           </Providers>
      </body>   
    </html>
  );
}
